# Rust formatting configuration
edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_block_trailing_comma = true
use_small_heuristics = "Default"
format_code_in_doc_comments = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80
imports_granularity = "Module"
group_imports = "StdExternalCrate"